#import "@local/note_template:0.1.0": *
#show: doc => note_template([Gaussian Mixture Model], doc)

#title()

The *gaussian mixture model (GMM)* is one of the simplest cases of probabilistic
model where some random variables are *latent*. This is similar to the Naive
Bayes model, except that we don't have observations for class labels, resulting
in a clustering algorithm similar to K-means.

The model can have different flavours but we will focus only on the main two
variants; what every variant has in common is the multinomial distribution that
models *labels* exactly like for a Naive Bayes.

One of the first and most simple variant is structured exactly like a Naive
Bayes but instead of $K$ multinomials for each of the $L$ features we have $K$
univariate gaussians, independent one another. This is exaclty a Gaussian Naive
Bayes but with latent class labels.

The other and more powerful variant is the one with $K$ multivariate gaussians,
which now considers a sample as a compound data and not like a composition of
independent features. The implication of this is that for each gaussian we have
a covariance matrix that in general is not diagonal.

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (p_pi, z, x, p_mu, p_sigma) = (
        (0, 0),
        (0, 0.75),
        (0, 1.5),
        (-0.75, 1.75),
        (0.75, 1.75),
      )

      node(p_pi, [$pi$])
      node(z, [$z$])
      node(x, [$x$], fill: aqua)
      node(p_mu, [$mu$])
      node(p_sigma, [$sigma$])

      edge(p_pi, "-|>", z)
      edge(z, "-|>", x)
      edge(p_mu, "-|>", x)
      edge(p_sigma, "-|>", x)
    },
  ),
  caption: [ Gaussian Mixture Model ],
) <fig-gmm>

Differently from K-means, the GMM is a *soft clustering* algorithm, which
technically computes only the probability for sample to belong to a particular
cluster $k$. In general every sample has nonzero probability of belonging to
each cluster.

In practice a GMM assumes that our data is generated by a *mixture of Gaussians*
($M$ Gaussians), and so a given observation $x$ is generated by the $m$-th
Gaussian with a certain probability

$ P(x | z = m) tilde cal(N) (mu_m, sigma_m) $

where $z$ is the *hidden mixture selection variable* with a multinomial prior

$ P(z = m) = pi_m $

and so the model parameters are

$ theta = (pi, mu, sigma) $

estimated by the EM algorithm.

= Generative Process

First of all let's consider the *generative process* of this model: if the model
has generated the data, it would have followed this procedure:

+ Given the parameter $pi$ of the multinomial, let's draw a cluster $m$ from the
  multinomial and assign it to $z$.
+ Use the value drawn from the previous step as index to choose which gaussian
  sample observations $x$ from.

Now we can try to write the *joint distribution* of this model by thinking about
the described generative process

$ P(X, Z | theta) = P(Z | pi) dot P(X | Z, mu, sigma) $

Which makes sense if we think it from a generative perspective in which first we
draw a cluster from the multinomial and then, using that index, we use the
$m$-th Gaussian to generate a sample.

= Learning

The next step is to learn the right parameters $theta$ of all the distribution
involved by solving the *learning inference problem* by Bayesian learning, ML or
MAP. Let's solve it by maximum likelihood, considering the *likelihood* we have
on observed data:

$ P(X | theta) $

but as @fig-gmm shows, $X$ is dependent on $Z$ and so we need to introduce it by
marginalization:

$
  P(X | theta) = sum_(m=1)^M P(X, Z = m | theta)
  = sum_(m=1)^M P(Z = m | theta) dot P(X | Z = m, theta)
$

and since each sample is i.i.d. we can write

$
  P(X | theta) & = product_(i=1)^N sum_(m=1)^M
                 P(z_i = m | pi) dot P(x_i | z_i = m, mu, sigma) \
               & = product_(i=1)^N sum_(m=1)^M
                 pi_m dot cal(N) (x_i | mu_m, sigma_m)
$

Now to avoid underflows we generally work in log-space and so we can obtain the
*log-likelihood*

$
  log P(X | theta) & = log(
                       product_(i=1)^N sum_(m=1)^M
                       pi_m dot cal(N) (x_i | mu_m, sigma_m)
                     ) \
                   & = sum_(i=1)^N log (sum_(m=1)^M
                       pi_m dot cal(N) (x_i | mu_m, sigma_m))
$

that is not nice to optimize directly by computing the derivative and setting it
to zero. What we can do instead is pretend to know $Z$ and use the *complete
likelihood*:

$ P(X, Z | theta) = P(Z | pi) dot P(X | Z, mu, sigma) $

Now a useful thing to do is to define *indicator variables*:

$
  z_(i m) = cases(
    1 & "if " z_i = m,
    0 & "otherwise"
  )
$

so we can now rewrite the complete likelihood like follows

$
  P(X, Z | theta) & = product_(i=1)^N product_(m=1)^M (
                      pi_m dot cal(N) (x_i | mu_m, sigma_m))^(z_(i m))
$

and so the complete log-likelihood becomes

$
  log P(X, Z | theta) = sum_(i=1)^N sum_(m=1)^M
  z_(i m) [ log pi_m + log cal(N) (x_i | mu_m, sigma_m) ]
$

That is in a much nicer form than before but now we introduced a new problem: in
practice we don't know $z_(i m)$ values so we still cannot directly optimize
this directly.

== Expectation Maximization

What we can do is use the *expectation maximization* algorithm, that iteratively
updates the parameters, starting from an initial guess. The idea is to

+ *E-step*: make the model predict every sample, generating the missing $z_(i m)$, based
  on some initial parameters.
+ *M-step*: update the parameters by maximizing the log-likelihood.

To make the model predict we need a posterior that, given an observation,
returns the most probable cluster based on the current parameters $theta^((k))$:

$ P(Z | X, theta^((k))) $

then we just need the likelihood to define a function that gathers the two:

$
  Q(theta | theta^((k))) & =
  sum_(m=1)^M P(Z = m | X, theta^((k))) log P(X, Z = m | theta) \
  & = EE_(m tilde P(Z | X, theta^((k)))) [ log P(X, Z = m | theta^((k))) ] \
$

By maximization of this function is now possible to find the parameters that are
most likely the right generators of data, since we put together a posterior and
a likelihood.

Since the function $Q$ is an expectation, we can write:

$
  Q(theta | theta^((k))) = EE_(P(Z = m | X, theta^((k))))
  [ sum_(i=1)^N sum_(m=1)^M z_(i m) [ log pi_m + log cal(N) (x_i | mu_m,
        sigma_m) ]]
$

and since the expectation is a linear operator, it can go inside the sum:

$
  Q(theta | theta^((k))) =
  sum_(i=1)^N sum_(m=1)^M EE_(P(Z = m | X, theta^((k)))) [ z_(i m) ]
  log(pi_m dot cal(N) (x_i | mu_m, sigma_m))
$

and since $z_(i m)$ are all zeros and ones we remain just with the posterior

$
  Q(theta | theta^((k))) =
  sum_(i=1)^N sum_(m=1)^M P(z_i = m | x_i, theta^((k))) dot
  log(pi_m dot cal(N) (x_i | mu_m, sigma_m))
$

so the last step is to compute this posterior by the Bayes rule:

$
  P(z_i = m | x_i) & = frac(P(x_i | z_i = m) dot P(z_i = m), P(x_i)) \
                   & = frac(
                       pi_m dot cal(N) (x_i | mu_m, sigma_m),
                       sum_m'^M pi_m' dot cal(N) (x_i | mu_m', sigma_m')
                     )
$

that gives us the *responsibilities* for each Gaussian to have generated a sample:

$
  r_(i m) = frac(
    pi_m dot cal(N) (x_i | mu_m, sigma_m),
    sum_m'^M pi_m' dot cal(N) (x_i | mu_m', sigma_m')
  )
$

and so we can finally define the full function $Q$ as


$
  Q(theta | theta^((k))) & = sum_(i=1)^N sum_(m=1)^M r_(i m) dot
  log(pi_m dot cal(N) (x_i | mu_m, sigma_m)) \
  & = sum_(i=1)^N sum_(m=1)^M r_(i m) dot log pi_m
  + sum_(i=1)^N sum_(m=1)^M r_(i m) dot log cal(N) (x_i | mu_m, sigma_m)
$

that we can now optimize by computing its derivative w.r.t. each parameter

$ pdv(Q, theta) = 0 $

At each iteration we can update the parameters like follows:

$
     pi_m & = N_m / N \
     mu_m & = 1 / N_m sum_(i=1)^N r_(i m) x_i \
  Sigma_m & = 1 / N_m sum_(i=1)^N r_(i m) (x_i - mu_m) (x_i - mu_m)^T
$

Keep in mind that since $pi$ is the parameter of a discrete random variable we
need to put also a sum to one constraint to get valid probabilities:

$ sum_(m=1)^M pi_m = 1 $

using Lagrangian multipliers.
