#import "@local/note_template:0.1.0": *
#show: doc => note_template([Gaussian Mixture Model], doc)

#title()

The *gaussian mixture model (GMM)* is one of the simplest cases of probabilistic
model where some random variables are *latent*. This is similar to the Naive
Bayes model, except that we don't have observations for class labels, resulting
in a clustering algorithm similar to K-means.

The model can have different flavours but we will focus only on the main two
variants; what every variant has in common is the multinomial distribution that
models *labels* exactly like for a Naive Bayes.

One of the first and most simple variant is structured exactly like a Naive
Bayes but instead of $K$ multinomials for each of the $L$ features we have $K$
univariate gaussians, independent one another. This is exaclty a Gaussian Naive
Bayes but with latent class labels.

The other and more powerful variant is the one with $K$ multivariate gaussians,
which now considers a sample as a compound data and not like a composition of
independent features. The implication of this is that for each gaussian we have
a covariance matrix that in general is not diagonal.

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (p_pi, z, x, p_mu, p_sigma) = (
        (0, 0),
        (0, 0.75),
        (0, 1.5),
        (-0.75, 1.75),
        (0.75, 1.75),
      )

      node(p_pi, [$pi$])
      node(z, [$z$])
      node(x, [$x$], fill: aqua)
      node(p_mu, [$mu$])
      node(p_sigma, [$sigma$])

      edge(p_pi, "-|>", z)
      edge(z, "-|>", x)
      edge(p_mu, "-|>", x)
      edge(p_sigma, "-|>", x)
    },
  ),
  caption: [ Gaussian Mixture Model ],
) <fig-gmm>

Differently from K-means, the GMM is a *soft clustering* algorithm, which
technically computes only the probability for sample to belong to a particular
cluster $k$. In general every sample has nonzero probability of belonging to
each cluster.

In practice a GMM assumes that our data is generated by a *mixture of Gaussians*
($M$ Gaussians), and so a given observation $x$ is generated by the $m$-th
Gaussian with a certain probability

$ P(x | z = m) tilde cal(N) (mu_m, sigma_m) $

where $z$ is the *hidden mixture selection variable* with a multinomial prior

$ P(z = m) = pi_m $

and so the model parameters are

$ theta = (pi, mu, sigma) $

estimated by the EM algorithm.

= Generative Process

First of all let's consider the *generative process* of this model: if the model
has generated the data, it would have followed this procedure:

+ Given the parameter $pi$ of the multinomial, let's draw a cluster $m$ from the
  multinomial and assign it to $z$.
+ Use the value drawn from the previous step as index to choose which gaussian
  sample observations $x$ from.

Of course the process could be slightly different depending on the GMM variant
we are using.

= Learning

In order to solve the *learning inference problem* we need the *joint
distribution* of this model (we will consider the simple case of univariate
gaussians):

$
  p(x, z | theta) & = p(z | pi) dot p(x | z, mu, sigma) \
                  & = p(z | pi) product_(l=1)^L p(x_l | z, mu_(m l), sigma_(m l)) \
                  & = product_(m=1)^M pi_m^(z_(i m)) (product_(l=1)^L
                      cal(N)(x_l | mu_(m l), sigma_(m l)))^(z_(i m))
$

with $z_(i m)$ indicator variable for the multinomial defined as

$ z_(i m) = cases(1 & "if " z_i = m, 0 & "otherwise") $

so that now we can write the joint probability for the full dataset assuming
that each sample is i.i.d., defining the *complete likelihood*:

$
  P(X, Z | theta) & = product_(i=1)^N product_(m=1)^M pi_m^(z_(i m))
  (product_(l=1)^L cal(N)(x_(i l) | mu_(m l), sigma_(m l)))^(z_(i m))
$

that can be turned as usual in the *complete log-likelihood*:

$
  log P(X, Z | theta) & = sum_(i=1)^N sum_(m=1)^M (z_(i m) log pi_m +
  z_(i m) sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)) \
  & = sum_(i=1)^N sum_(m=1)^M z_(i m) (log pi_m +
    sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)))
$

The multivariate gaussian formula is basically the same but we don't have the
sum over $L$ features.

== Expectation Maximization

Now since we want to learn by *maximum likelihood* but we miss $z_(i m)$ values,
we have to perform use the *expectation maximization* algorithm, starting by the
$Q$ function:

$
  Q(theta | theta^((k))) & = EE_P(Z | X, theta^((k))) [log P(X, Z = m | theta)] \
  & = EE_P(Z | X, theta^((k))) [sum_(i=1)^N sum_(m=1)^M
    z_(i m) (log pi_m + sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)))] \
  & = sum_(i=1)^N sum_(m=1)^M EE_P(z_i = m | x_i, theta^((k))) [
    z_(i m) (log pi_m + sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)))] \
  & = sum_(i=1)^N sum_(m=1)^M EE_P(z_i = m | x_i, theta^((k))) [ z_(i m) ]
  (log pi_m + sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l))) \
$

and since $z_(i m)$ can only have values only in ${0, 1}$ we can directly write

$
  Q(theta | theta^((k))) = sum_(i=1)^N sum_(m=1)^M
  P(z_i = m | x_i, theta^((k)))
  (log pi_m + sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)))
$

Using the Bayes rule, the *posterior* for one sample $x_i$, is defined as

$
  p(z_i = m | x_i, theta^((k))) & = frac(
                                    p(z_i = m | theta^((k))) dot
                                    p(x_i | z_i = m, theta^((k))),
                                    p(x_i | theta^((k)))
                                  ) \
                                & = frac(
                                    p(z_i = m | theta^((k))) product_(l=1)^L
                                    p(x_(i l) | z_i = m, theta^((k))),
                                    sum_m'^M
                                    p(x_i, z = m' | theta^((k)))
                                  ) \
                                & = frac(
                                    pi_m product_(l=1)^L
                                    cal(N)(x_(i l) | mu_(m l), sigma_(m l)),
                                    sum_m'^M pi_m'
                                    product_(l=1)^L cal(N)(x_(i l) | mu_m', sigma_m')
                                  ) = r_(i m)
$

with $r_(i m)$ being the responsibilities that each gaussian have for the
generation of a sample $x_i$. So now we can substitute:

$
  Q(theta | theta^((k))) & = sum_(i=1)^N sum_(m=1)^M r_(i m)
  (log pi_m + sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l))) \
  & = sum_(i=1)^N sum_(m=1)^M r_(i m) log pi_m
  + sum_(i=1)^N sum_(m=1)^M r_(i m)
  sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l))
$

The last step is to find the optimal values for the parameters each step of the
algorithm; let's start with $pi_m$ and considering only the first term of the
$Q$ function and defining the Lagrangian:

$
  J(pi, lambda) = sum_(i=1)^N sum_(m=1)^M r_(i m) log pi_m +
  lambda (sum_(m=1)^M pi_m - 1)
$

from which we can derive

$ pdv(J, pi_m) = r_(i m) / pi_m + lambda = 0 <==> pi_m = - r_(i m) / lambda $

and by enforcing the constraint we get

$ sum_(m=1)^M pi_m - 1 = 0 <==> lambda = - sum_(m=1)^M r_(i m) $

finally obtaining

$ pi_m = r_(i m) / (sum_(m=1)^M r_(i m)) $

For the parameter $mu_(m l)$ and $sigma_(m l)$ we can instead optimize the
second term

$
  J(mu, sigma) & = sum_(i=1)^N sum_(m=1)^M r_(i m)
                 sum_(l=1)^L log cal(N)(x_(i l) | mu_(m l), sigma_(m l)) \
               & = sum_(i=1)^N sum_(m=1)^M r_(i m)
                 sum_(l=1)^L (- frac((x_(i l) - mu_(m l))^2, 2 sigma_(m l)^2)
                   - log sqrt(2 pi) sigma_(m l)) \
               & = - sum_(i=1)^N sum_(m=1)^M r_(i m)
                 sum_(l=1)^L frac((x_(i l) - mu_(m l))^2, 2 sigma_(m l)^2)
                 - sum_(i=1)^N sum_(m=1)^M r_(i m)
                 sum_(l=1)^L log sqrt(2 pi) sigma_(m l)
$

Taking the derivarive w.r.t. $mu_(m l)$ and $sigma_(m l)$ gives us

$
  pdv(J, mu_(m l)) = 0 <==> mu_(m l) = frac(
    sum_(i=1)^N r_(i m) x_(i l),
    sum_(i=1)^N r_(i m)
  ) \
  pdv(J, sigma_(m l)) = 0 <==> sigma_(m l)^2 = frac(
    sum_(i=1)^N r_(i m) (x_(i l) - mu_(m l))^2,
    sum_(i=1)^N r_(i m)
  )
$

So now we are able to update $theta^((k))$ at each step.

