#import "@local/note_template:0.1.0": *
#show: doc => note_template([Recurrent Encoder-Decoder], doc)

#title()

Standard RNNs and gated models are not well suited for sequence-to-sequence task
where there is an asymmetry between the input sequence and the output sequence.
For example in sequence transduction of natural language sentences, we might
have a sentence that cannot be translated word by word using the same number and
order of words.

In this sense we want something that completely elaborate a sequence, build a
representation of it and produce and output sequence that is meaningful.

Naively we can think of a recurrent model which elaborates every token, does not
produce any output but only updates its hidden state. In the end uses $h_T$ as
only input to produce the output sequence. In this setting each output token is
generated by taking in input only the previous hidden state representation. This
doesn't work really so we need a more powerful architecture.

= Encoder-Decoder Architecture

The idea of *recurrent encoder-decoder* is to explicitly separate an *encoder*
model, encharged of producing a *context*, which can be as before, just the last
hidden state produced

$ c = h_T $

with each hidden state produced with the usual recurrent dynamic

$ h_t = W_h h_(t-1) + b_h $

The difference w.r.t. the previous naive approach is that now this context is
unchanged for the full decoding part.

#figure(
  image("images/encoder.png", width: 70%),
  caption: [ Encoder ],
)

The *decoder*, at each step, takes in input the context $c$, the previously
generated hidden state $s_(t-1)$ and the previously generated output $y_(t-1)$
in order to update its own hidden state

$ s_t = W_c c + W_s s_(t-1) + W_"in" y_(t-1) $

and _autoregressively_ generating the next output token $y_t$:

$ y_t = W_"out" s_t $

#figure(
  image("images/decoder.png", width: 70%),
  caption: [ Decoder ],
)

#note[ Inverting the input sequence can improve the performance. ]

= Attention

The problem of that architecture is how the context is built. We still have a
fixed size tensor that embeds the full story of a sequence, and this can be a
problem for long sequences because the context could be too small to capture
important informations or too large that introduce computational issues.

Ideally we want something that, in order to generate a new token, look at the
full sequence, or at the full sequence of hidden states, to be able to focus
only on the most relevant parts.

The advantage is also that an early generated hidden state might be gone
(partially or entirely) in the full context $c$. In this way we can look at its
full representation back in the history.

The *attention* mechanism receives in input every intermediate representation of
the input sequence

#figure(
  image("images/attention.png", width: 60%),
  caption: [ Attention ],
)

== Soft Attention

A popular implementation of attention is the *soft attention*, which takes in
input all the encodings of the input sequence $h_i$ and the current decoder
state $s_(t-1)$ producing a per-output token context $c_t$.

#figure(
  image("images/soft_attention.png", width: 50%),
  caption: [Soft Attention Module],
)

The shift here is that we want a better context for each $y_t$ we are trying to
produce. The encoder is now encharged of producing only the sequence of hidden
states $h_t$. After that the attention module takes in input all of them and the
current decoder state $s_(t-1)$, producing a context $c_t$. That context is than
use as before to update the decoder state:

$ s_t = W_c c_t + W_s s_(t-1) + W_"in" y_(t-1) $

and _autoregressively_ generate the next output token $y_t$:

$ y_t = W_"out" s_t $

In practice the attention module is composed of three main stages. The attention
module has a neural network inside that takes input the decoder state $s_(t-1)$
and, once at a time, the hidden states $h_i$, for each timestep producing in
output a *score*.

$ e_(t, i) = a(s_(t-1), h_i) $

where $a$ is the NN and a common choice is

$ e_(t i) = v^TT tanh(W_s s_(t-1) + W_h h_i + b) $

where $v$ is a learnable parameter that measures an interaction element-wise.

Once obtained the scores they are passed into a *softmax*, obtaining a
probability distribution:

$ alpha_i = frac(exp(e_(t i)), sum_(j=1)^n exp(e_(t j))) $

where $n$ is the number of hidden states $h_i$.

Now that we have proportions $alpha_i$ we can multiply each hidden state $h_i$
by its proportion

$ alpha_i h_i $

in order to model how much of that hidden state we want in the context. In the
end the *aggregation* step simply sum over all the proportioned hidden states:

$ c_t = sum_(i=1)^n alpha_i h_i $

producing the context $c_t$ used to predict the token $c_t$.

=== Cross Attention

In sequence-to-sequence modelling where we have a sequence in input and a target
sequence in output that are different, for example in sequence transduction, we
are talking about *cross attention*.

The intuition is that we need a mechanism to relate two different sequences,
emphasizing which parts of the input sequence is more relavant to predict each
token of the output sequence.

== Hard Attention

A variant of soft attention is *hard attention* which is identical to soft
attention up to part where each input hidden state $h_i$ is proportioned to its
probability $alpha_i$.

#figure(
  image("images/hard_attention.png", width: 60%),
  caption: [ Hard Attention ],
)

The difference lie in the aggregation step, in which instead of merging
everything to create the context, only one $alpha_i h_i$ is sampled, each with
probability $alpha_i$ generating the context, that this time will be

$ c_t = alpha_i h_i $

Reducing computational cost for long sequences but breaking differentiability.

== Local Attention

Another variant is *local attention* which adds a neural network whose input is
the decoder state $s_(t-1)$ and for each sequence token, predicts $1$ if that
token should partecipate or $0$ otherwise.

#figure(
  image("images/local_attention.png", width: 70%),
  caption: [ Hard Attention ],
)

Here the intuition is that the neural network directly turns off signals that
are not interesting, probably those that are far in the sequence w.r.t. to the
token we are trying to predict.

== Interpretability of Attention

Attention is also much more interpretable than many other methods, because it
emphasize alignment between sequences, in particular between pairs of tokens
from the input and output sequence.

