#import "@local/note_template:0.1.0": *
#show: doc => note_template([Recurrent Encoder-Decoder], doc)

#title()

Standard RNNs and gated models are not well suited for sequence-to-sequence task
where there is an asymmetry between the input sequence and the output sequence.
For example in sequence transduction of natural language sentences, we might
have a sentence that cannot be translated word by word using the same number and
order of words.

In this sense we want something that completely elaborate a sequence, build a
representation of it and produce and output sequence that is meaningful.

Naively we can think of a recurrent model which elaborates every token, does not
produce any output but only updates its hidden state. In the end uses $h_T$ as
only input to produce the output sequence. In this setting each output token is
generated by taking in input only the previous hidden state representation. This
doesn't work really so we need a more powerful architecture.

The idea of *recurrent encoder-decoder* is to explicitly separate an *encoder*
model, encharged of producing a *context*, which can be as before, just the last
hidden state produced

$ c = h_T $

The difference w.r.t. the previous approach is that now this context is
unchanged for the full decoding part. The *decoder*, at each step, takes in
input the context $c$, the previously generated hidden state $s_(t-1)$ and the
previously generated output $y_(t-1)$

#figure(
  image("images/decoder.png", width: 70%),
  caption: [ Decoder ],
)

_autoregressively_ generating the next hidden state $h_t$ and output token
$y_t$.

#note[
  Iverting the input sequence can improve the performance.
]

= Attention

The problem of that architecture is how the context is built. We still have a
fixed size tensor that embeds the full story of a sequence, and this can be a
problem for long sequences because the context could be too small to capture
important informations or too large that introduce computational issues.

Ideally we want something that, in order to generate a new token, look at the
full sequence, or at the full sequence of hidden states, to be able to focus
only on the most relevant parts.

The advantage is also that an early generated hidden state might be gone
(partially or entirely) in the full context $c$. In this way we can look at its
full representation back in the history.

The *attention* mechanism receives in input every intermediate representation of
the input sequence

#figure(
  image("images/attention.png", width: 60%),
  caption: [ Attention ],
)

== Soft Attention

A popular implementation of attention is the *soft attention*, which takes in
input all the encodings of the input sequence $h_i$ and the current decoder
state $s_(t-1)$.

#figure(
  image("images/soft_attention.png", width: 50%),
  caption: [Soft Attention Module],
)

// explain the full story from encoder to decoder !!!

