#import "@local/note_template:0.1.0": *
#show: doc => note_template([Structure Learning], doc)

#title()

When we have a dataset, and so observations on data, we might want to build a
model (whatever we choose) only by looking at the data. This basically means to
build a structure of conditional dependences among variables, in order to run a
learning algorithm in learn the parameters of each random variable distribution.

In *structure learning* we work under the assumption that a *true model or
structure* exists and we are interested in finding it. Let's precise that, based
on the assumptions we make on the model, we can obtain different results. For
example we may be interested in build a Bayesian network that is _markovian_ and
_faithful_ to the distribution, or maybe a causal model that also have the
_sufficiency_ property; different choices of assumptions result in different
results and different algorithms to build the wanted structure.

A fundamental concept in structure learning is *Markov equivalence class (MEC)*
that let us define a set of possible graphs (DAGs) that are equivalent; in fact
usually structure learning algorithms returns a MEC and not a single graph.

#important(title: [Markov Equivalence Class])[
  A *Markov equivalence class* is a set of DAGs encoding the same set of
  conditional independences.

  Two DAGs are *Markov equivalent* if and only if they have the same *skeleton*
  and same set of colliders (_v-structures_).
]

The _skeleton_ of a DAG is basically the DAG itself without edges. MECs can be
encoded by *partially completed DAGs (CPDAG)*, that are DAGs where edges that
differs in the MEC, between different DAGs are undirected.

#figure(
  image("images/MEC.png", width: 40%),
  caption: [ Markov Equivalence Class and its CPDAG ],
)

Of course there are ways in which is possible to reduce the obtained MEC, so
that more edges are directed and we don't need to choose among different
combinations.

= Constraint-Based

The first approach to structure learning is the *constraint-based*, that uses
*conditional independence tests* to reconstruct the Markov equivalence class, by
assuming _markov property_, _faithfulness_ and _sufficiency_.

== SGS

One of the main algorithms is the *SGS*, that says that

- Two variables $X$ and $Y$ are adjacent in the skeleton if they are always
  conditionally dependent, so there is no separating set without $X$ and $Y$.
- If $X$ and $Y$ are not adjacent in the skeleton, then exists a third variable
  $W$ that
  - It's adjacent to both $X$ and $Y$
  - Is not a member of any separating set
  that basically means that $W$ is a collider.

The first part of the algorithm finds the skeleton starting from a fully
connected and undirected graph and, by performing conditional independence
tests, removes edges among nodes that are conditionally independent given a
separating set.

Assuming our dataset was generated by the DAG on the left (that we don't have)
and we need, starting from the graph on the right, we have to reconstruct the
skeleton.

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (A, B, C, D) = (
        (0, 0),
        (-0.75, 0.75),
        (0.75, 0.75),
        (0, 1.5),
      )
      node(A, [$A$])
      node(B, [$B$])
      node(C, [$C$])
      node(D, [$D$])

      edge(A, "-|>", B)
      edge(A, "-|>", C)
      edge(B, "-|>", D)
      edge(C, "-|>", D)

      let (A, B, C, D) = (
        (3, 0),
        (2.25, 0.75),
        (3.75, 0.75),
        (3, 1.5),
      )
      node(A, [$A$])
      node(B, [$B$])
      node(C, [$C$])
      node(D, [$D$])

      edge(A, "-", B)
      edge(A, "-", C)
      edge(A, "-", D)
      edge(B, "-", C)
      edge(B, "-", D)
      edge(C, "-", D)
    },
  ),
)

and this can be done by considering one couple of nodes at a time and run CI
tests, in order to remove edges. For example $A$ and $B$ are always dependent
one another because there is no separating set for them, so the edge between
them remains.

For $A$ and $D$ instead, we will have that

$ "CI"(A, D | B, C) = "True" $

so we have to remove the edge between them. Similar result for $B$ and $C$ that
are separated by $A$. So in the end we obtain the following skeleton

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (A, B, C, D) = (
        (0, 0),
        (-0.75, 0.75),
        (0.75, 0.75),
        (0, 1.5),
      )
      node(A, [$A$])
      node(B, [$B$])
      node(C, [$C$])
      node(D, [$D$])

      edge(A, "-", B)
      edge(A, "-", C)
      edge(B, "-", D)
      edge(C, "-", D)
    },
  ),
)

Once we have the skeleton, we need to give a orientation to the edges and this
can be partially done by finding colliders (because they are the only ones
identifiable from data). In this particular case, if we consider the triplet
$B$, $C$ and $D$, we have that $B$ and $C$ are not adjacent in the graph and $D$
is not in their separating set (before we saw that only $A$ is in their
separating set). So we can conclude that $D$ is collider.

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (A, B, C, D) = (
        (0, 0),
        (-0.75, 0.75),
        (0.75, 0.75),
        (0, 1.5),
      )
      node(A, [$A$])
      node(B, [$B$])
      node(C, [$C$])
      node(D, [$D$])

      edge(A, "-", B)
      edge(A, "-", C)
      edge(B, "-|>", D)
      edge(C, "-|>", D)
    },
  ),
)

Since we already found all colliders, we can infer more orientations by applying
the *Meek rules*

#figure(
  image("images/meek_rules.png", width: 50%),
  caption: [ Meek Rules ],
)

that basically exploit the fact that there are no more colliders to be found,
otherwise we would have find them in the previous step. Hence, even though there
are possible configurations of inderected edges that could form a collider, they
cannot be in the true structure of the model, so they are discarded.

#figure(
  diagram(
    node-shape: "circle",
    node-stroke: 1pt,
    edge-stroke: 1pt,
    {
      let (A, B, C, D) = (
        (0, 0),
        (-0.75, 0.75),
        (0.75, 0.75),
        (0, 1.5),
      )
      node(A, [$A$])
      node(B, [$B$])
      node(C, [$C$])
      node(D, [$D$])

      edge(A, "<|-", B)
      edge(A, "<|-", C)
      edge(B, "-|>", D)
      edge(C, "-|>", D)
    },
  ),
  caption: [ Not Possible DAG ],
)

Other rules exploit the fact the a DAG, by definition, cannot have cycles.

== PC

The *PC* algorithm basically does the same two iterative steps of SGS but,
instead of considering all the separating sets, it considers separating sets of
increasing size. This has a better time complexity on average.

== Testing Strategy

In order to avoid the super exponential complexity of SGS is fundamental to
choose a convenient ordering of testing.

- *Level-wise*: conditioning sets of increasing size (PC algorithm)
- *Node-wise*: one edge at a time, exhausting all possible conditioning sets.
- *Neighborhood*: choose from the neighborhood of the nodes incident on the edge.

Let's also point out that, if we are interested only in one particular relation
$X -> Y$, is possible to find a subgraph containing $X$ and $Y$, and their
adjustment sets (*local causal discovery*).

== Conclusions on Constraint-Based Methods

The CPDAG produced by those methods is enough to answer probabilistic queries
$P(Y | X)$, by just picking one graph in the MEC.

Instead for interventional and counterfactuals queries we need further knowledge
to orient all edges.

Let's also add that, given the graph, we need to choose the distribution
families or the mechanisms and learn the parameters. So the more are the
variables the more CI tests are needed, but this is kind of independent from the
structure learning method.

= Search and Score

Another possible way to find structures is by *search and score*, a.k.a *model
selection*, where we search in *graph space* $"Graph"(Y)$ of all the possible
graphs that can be built with the set of variables $Y$, score each structure and
choose the best one.

== Score Function

The way to see how well the graph fits data is through a *score function*, that
must satisfy two main properties:

- *Consistency*: same score for graphs in the same equivalence class.
- *Decomposability*: can be locally computed.

And there are two families of approaches for these functions:

- *Information theoretic*: based on data likelihood plus some model complexity
  penalization term.
- *Bayesian*: score the structures using a graph posterior (likelihood and a
  proper prior choice).

A popular choice is the *bayesian information criterion (BIC)*, defined as

$ S(cal(G); D) = log p_hat(theta) (D | cal(G)) - k/2 log n $

with $n$ the number of samples and $k$ the number of parameters (can be the
number of edges). The BIC is *consistent* and *local*.

== Search Strategy

Finding maximal scoring structures is NP-complete so we need a strategy to make
the search feasible:

- *Constrain search strategy*: starting from a candidate structure that is
  iteratively modified by local operations.
- *Constrain search space*: search in some reduced space with interesting properties.

=== GES

The *greedy equivalent search (GES)*  is from the second type of approach, in
fact it searches in the MEC, by performing three different operations:

- *Insertion*: add an edge leading to a different MEC.
- *Deletion*: remove an edge leading to a different MEC.
- *Reversal*: flip an edge leading to a different MEC.

The algorithm greedly tries all possible combinations of those three operations
and, by using the BIC score, the GES ensures to find the MEC of the true DAG.

= Better than MEC

Both methods return a MEC and without prior additional knowledge or
interventions is not possible to do better.

#note(title: [Pearl and Geiger])[
  For heteroskedastic *linear Gaussian* and *multinomial* causal relations, an
  algorithm that identifies the *Markov equivalence class* of the true model is
  *complete*.
]

There are some cases in which we can actually do better, for example with ANM.
