#import "@local/note_template:0.1.0": *
#show: doc => note_template([Variational Autoencoders], doc)

#title()

The *variational autoencoder* aims to explicitly learn a distribution density,
making possible to better organize the latent space in order to also generate
significative samples from it.

The model can be seen as completely probabilistic, to better understand all the
components involved. In fact we can define the *generative process* of it, by
assuming that observations are generated by some latent variable (the latent
space), and then decoded by a *conditional decoder* from latent space to data
space:

+ Sample a latent code from the prior distribution, typically defined as a
  normal $z tilde cal(N)(0, I)$.
+ Generate a data sample through the conditional decoder distribution
  $x tilde p_theta (x | z)$

This process defines the *joint distribution* of the model as

$ p_theta (x, z) = p_theta (x | z) p(z) $

and the corresponding marginal data density:

$
  p_theta (x) = integral p_theta (x, z) dd(z) = integral p_theta (x | z) p(z) dd(z)
$

And since we are dealing with latent variable model we would like to perform
learning through EM algorithm, so we need a tractable posterior

$ p_theta (z | x) = frac(p_theta (x | z) p(z), p_theta (x)) $

but as we know, the posterior is often intractable due to the marginal data
distributiion, that in general, is intractable. Therefore, we need to introduce
a *variational posterior* $q_phi.alt (z | x)$ in order to perform learning.

The novelty w.r.t. a "pure" probabilistic model and also a classic autoencoder,
is that now the variational posterior $q_phi.alt (z | x)$ is parameterized by a
neural encoder, that directly outputs the parameters of a Gaussian:

$ q_phi.alt (z | x) cal(N)(mu_phi.alt (x), diag(sigma_phi.alt^2 (x))) $

This defines a sort of ammortized E-step for the EM algorithm, instead of
computing an exact posterior for each sample.

The decoder then receives a sampled latent code $z tilde q_phi.alt (z | x)$ and
defines a *reconstruction distribution* $p_theta (x | z)$.

In this sense we have a architectural shift from the classical autoencoders:

- Deterministic encoding becomes stochastic inference.
- Deterministic decoding becomes conditional generation.
- Reconstruction becomes likelihood-based learning.

